### PR TITLE
Edit ruleset rules endpoint

### LINKED ISSUE #36: Edit ruleset rules endpoint
Endpoint: `PATCH /i/rulesets/<path>`

Expected payload :
```js
{
  "rules": [
        {
            "sExpr": "",
            "returnValue": "",
        }
    ]
}
```

The server must replace all the rules of the ruleset by the ones received in the request.

## Success
Response: 200

## Failure
Requirements: The `rules` field of the payload must contain at least one rule

Validation error:
```js
{ 
	"error": "validation",
	"fields": [
		{
			"path": ["rules", "2", "sExpr"],
			"error": {
				"message": "",
				"line": 10,
				"char": 11,
				"absChar": 120,
			}
		},
		{
			"path": ["rules", "2", "returnValue"],
			"error": {
				"message": "",
			}
		}
	]
}
```

### PR DESCRIPTION
**Pull request by tealeg**
Fixes #36 

This PR adds a handler for editing a Rulesets rules.  

Along the way I also:
- corrected the `PutFn` function of the mock `RulesetService`
- added a convenience method for deriving `sexpr.Paramaters` from `regula.Signature` types

### CODE REVIEW

File: ui/handler.go [hunk 1]
```diff
@@ -121,6 +121,94 @@ func (h *internalHandler) handleNewRulesetRequest(w http.ResponseWriter, r *http
...
+	if path == "" {
+		writeError(w, r, nil, http.StatusNotFound)
+		return
+	}
+
+	nrr := &newRulesetRequest{}
+
+	err := json.NewDecoder(r.Body).Decode(nrr)
+	if err != nil {
+		writeError(w, r, err, http.StatusInternalServerError)
```
Comment (asdine) [inline ui/handler.go]: This should be a `http.StatusBadRequest` instead as it's the client's fault

File: ui/handler.go [hunk 2]
```diff
@@ -121,6 +121,94 @@ func (h *internalHandler) handleNewRulesetRequest(w http.ResponseWriter, r *http
...
+		if err == store.ErrNotFound {
+			writeError(w, r, err, http.StatusNotFound)
+			return
+		}
+
+		writeError(w, r, err, http.StatusInternalServerError)
+		return
+	}
+	if result == nil {
+		err := fmt.Errorf("No Ruleset found at path: %q", path)
```
Comment (asdine) [inline ui/handler.go]: :tulip: No uppercase on errors

File: ui/handler.go [hunk 3]
```diff
@@ -121,6 +121,94 @@ func (h *internalHandler) handleNewRulesetRequest(w http.ResponseWriter, r *http
...
+		writeError(w, r, err, http.StatusNotFound)
+		return
+	}
+	reghttp.EncodeJSON(w, r, nil, http.StatusNoContent)
```
Comment (asdine) [inline ui/handler.go]: Do we need to call `EncodeJSON` for that?

Does that work too?

```go
w.WriteHeader(http.StatusNoContent)
```

File: ui/handler.go [hunk 4]
```diff
@@ -121,6 +121,94 @@ func (h *internalHandler) handleNewRulesetRequest(w http.ResponseWriter, r *http
...
+	err, status := updateEntry(entry, nrr)
+	if err != nil {
+		writeError(w, r, err, status)
+		return
+	}
+
+	// Write the new entry back to the DB
+	result, err := h.service.Put(r.Context(), path, entry.Ruleset)
+	if err != nil {
+		if err == store.ErrNotFound {
```
Comment (YassineE) [inline ui/handler.go]: The `Put` method will never return the `store.ErrNotFound` error. 
Only `store.ErrNotModified` can be returned.

File: ui/handler.go [hunk 5]
```diff
@@ -121,6 +121,94 @@ func (h *internalHandler) handleNewRulesetRequest(w http.ResponseWriter, r *http
...
+	if result == nil {
+		err := fmt.Errorf("No Ruleset found at path: %q", path)
+		writeError(w, r, err, http.StatusNotFound)
+		return
+	}
+	reghttp.EncodeJSON(w, r, nil, http.StatusNoContent)
+}
+
+// updateEntry augments an existing entry with new Rules
+func updateEntry(entry *store.RulesetEntry, nrr *newRulesetRequest) (error, int) {
```
Comment (YassineE) [inline ui/handler.go]: Is not a Go antipattern to return the error first?

File: ui/handler.go [hunk 6]
```diff
@@ -134,6 +222,8 @@ func (h *internalHandler) handleSingleRuleset(w http.ResponseWriter, r *http.Req
 
 	entry, err := h.service.Get(r.Context(), path, "")
 	if err != nil {
+		logger := reghttp.LoggerFromRequest(r)
+		logger.Debug().Msg("foo")
```
Comment (YassineE) [inline ui/handler.go]: I think that this debug can be removed.

File: ui/handler.go (hunk 4 above)
Comment (YassineE) [reply ui/handler.go]: When saying "Only", I mean only ErrNotModified can be returned from our internal types error.

File: ui/handler.go (hunk 5 above)
Comment (tealeg) [reply ui/handler.go]: Good point - I went this way because it's additional data that you only care about when there is an error, but it definitely looks weird.

File: ui/handler.go (hunk 6 above)
Comment (tealeg) [reply ui/handler.go]: Agreed :-)

File: ui/handler.go (hunk 1 above)
Comment (tealeg) [reply ui/handler.go]: Done

File: ui/handler.go (hunk 2 above)
Comment (tealeg) [reply ui/handler.go]: Done

File: ui/handler.go (hunk 3 above)
Comment (tealeg) [reply ui/handler.go]: :+1:

File: ui/handler.go (hunk 4 above)
Comment (tealeg) [reply ui/handler.go]: You are correct.  Thanks, good catch.

File: ui/handler.go [hunk 7]
```diff
@@ -121,6 +121,89 @@ func (h *internalHandler) handleNewRulesetRequest(w http.ResponseWriter, r *http
...
+	status, err := updateEntry(entry, nrr)
+	if err != nil {
+		writeError(w, r, err, status)
+		return
+	}
+
+	// Write the new entry back to the DB
+	result, err := h.service.Put(r.Context(), path, entry.Ruleset)
+	if err != nil {
+		writeError(w, r, err, http.StatusInternalServerError)
```
Comment (YassineE) [inline ui/handler.go]: I am afraid that if a ruleset is submitted without any changes the `Put` method will return `store.ErrNotModified` and here we will return `http.StatusInternalServerError`.

Comment (tealeg) [reply ui/handler.go]: OK. I'll add a test case and handle that appropriately.  :+1:

Comment (tealeg) [reply ui/handler.go]: DOne

Comment (tealeg) [reply ui/handler.go]: :up: @YassineE
